
[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.10.0"

[[constraint]]
  branch = "master"
  name = "github.com/function61/gokit"

[prune]
  go-tests = true
  unused-packages = true
